/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pjatk.byt.sms.frame;

/**
 *
 * @author Pawel
 */
public class AddProducts extends javax.swing.JFrame {

    /**
     * Creates new form AddProducts
     */
    public AddProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        categoryLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        brandLabel = new javax.swing.JLabel();
        brandComboBox = new javax.swing.JComboBox<>();
        unitsLabel = new javax.swing.JLabel();
        unitsInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        statusLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));
        setForeground(new java.awt.Color(0, 204, 153));
        setMaximumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(null);

        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("              Przyjmij dostawę");
        getContentPane().add(headerLabel);
        headerLabel.setBounds(135, 11, 191, 37);

        backButton.setText("Powrót");
        backButton.setMaximumSize(new java.awt.Dimension(107, 23));
        backButton.setMinimumSize(new java.awt.Dimension(107, 23));
        backButton.setPreferredSize(new java.awt.Dimension(107, 23));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(534, 337, 107, 44);

        categoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        categoryLabel.setText("Kategoria");
        getContentPane().add(categoryLabel);
        categoryLabel.setBounds(78, 90, 100, 14);

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WYBIERZ", "OPONA", "FELGA" }));
        categoryComboBox.setOpaque(false);
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(categoryComboBox);
        categoryComboBox.setBounds(78, 119, 110, 23);

        brandLabel.setForeground(new java.awt.Color(255, 255, 255));
        brandLabel.setText("Marka");
        getContentPane().add(brandLabel);
        brandLabel.setBounds(195, 90, 100, 14);

        brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WYBIERZ" }));
        getContentPane().add(brandComboBox);
        brandComboBox.setBounds(195, 119, 120, 23);

        unitsLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitsLabel.setText("Ilość");
        getContentPane().add(unitsLabel);
        unitsLabel.setBounds(414, 90, 60, 14);

        unitsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitsInputActionPerformed(evt);
            }
        });
        getContentPane().add(unitsInput);
        unitsInput.setBounds(414, 119, 40, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Średnica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(325, 90, 80, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13\"", "16\"", "18\"" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(325, 119, 60, 23);

        statusLabel.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(statusLabel);
        statusLabel.setBounds(200, 210, 130, 20);

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorLabel);
        errorLabel.setBounds(202, 184, 130, 20);

        addProductButton.setText("Dodaj");
        addProductButton.setMaximumSize(new java.awt.Dimension(107, 23));
        addProductButton.setMinimumSize(new java.awt.Dimension(107, 23));
        addProductButton.setPreferredSize(new java.awt.Dimension(107, 23));
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addProductButton);
        addProductButton.setBounds(534, 110, 107, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgroundFrame.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 836, 449);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManagerViewFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
        if (categoryComboBox.getSelectedItem().equals("OPONA")){
            brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WYBIERZ", "CONTINENTAL", "DUNLOP", "BRIDGESTONE", "NOKIAN", "FULDA", "MICHELIN" , "DĘBICA" , "DAYTON"  }));
        } else if (categoryComboBox.getSelectedItem().equals("FELGA")) {
            brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WYBIERZ", "DOTZ", "CARMANI", "TSR", "RIAL", "INFINY", "BORBET" , "ATS" , "ALUTEC"  }));
        }
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void unitsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitsInputActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        errorLabel.setText("");
        statusLabel.setText("");
        if (categoryComboBox.getSelectedItem().equals("WYBIERZ")) {
            errorLabel.setText("Wybierz kategorię!");
        } else if (brandComboBox.getSelectedItem().equals("WYBIERZ")) {
            errorLabel.setText("Wybierz markę!");
        } else if (unitsInput.getText().equals("")) {
            errorLabel.setText("Wprowadź ilość!");
        } else {
            statusLabel.setText("Produkt został dodany!");
            unitsInput.setText("");
        } 
    }//GEN-LAST:event_addProductButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> brandComboBox;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField unitsInput;
    private javax.swing.JLabel unitsLabel;
    // End of variables declaration//GEN-END:variables
}
