/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pjatk.byt.sms.frame;


public class ProductListFrame extends javax.swing.JFrame {

    /**
     * Creates new form ListaProduktow
     */
    public ProductListFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productListTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(null);

        jButton1.setText("Powrót");
        jButton1.setMaximumSize(new java.awt.Dimension(107, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(107, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(107, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 330, 107, 38);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista Produktów");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(117, 11, 130, 14);

        productListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EAN", "KATEGORIA", "MARKA", "CENA SZT.", "ILOŚĆ"
            }
        ));
        jScrollPane1.setViewportView(productListTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 127, 470, 250);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Szukaj:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 100, 14);

        jButton2.setText("Sprzedaj");
        jButton2.setMaximumSize(new java.awt.Dimension(107, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(107, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(107, 23));
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 150, 107, 37);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgroundFrame.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(700, 450));
        jLabel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel3.setPreferredSize(new java.awt.Dimension(836, 449));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-60, 0, 836, 449);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManagerViewFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productListTable;
    // End of variables declaration//GEN-END:variables
}
